---
abstract: 'DOCTYPE based XML output'
author:
  - 'Barrie Slaymaker <barries@slaysys.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.87'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-AutoWriter
no_index:
  directory:
    - inc
    - t
requires:
  perl: 5.6.1
resources:
  license: http://opensource.org/licenses/bsd-license.php
version: 0.4
